### ISSUE TITLE
Errors with standalone checks (i.e. the "subscribers" property isn't defined)

### ISSUE THREAD

**Issue by swvjeff** [sensu-plugins/sensu-plugins-twilio#4]
According to the Sensu docs ([here](https://sensuapp.org/docs/latest/checks) and [here](https://sensuapp.org/docs/latest/getting-started-with-checks)), standalone checks don't require a "subscribers" array in its JSON config. When I created a standalone check and omitted the subscribers array, the Twilio handler failed with the following error:

`/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugins-twilio-0.0.3/bin/handler-twiliosms.rb:40:in &': no implicit conversion of nil into Array (TypeError)`

**Comment by eheydrick** [comment]
Looks like #5 addresses this.

**Comment by eheydrick** [comment]
Can you try version 1.0.0.

**Comment by majormoses** [comment]
closing due to lack of confirmation from user and it is likely fixed.
